apiVersion: v1
kind: ReplicationController
metadata:
  namespace: demos
  name: frontend
spec:
  replicas: 5
  template:
    metadata:
      labels:
        demo: frontend
    spec:
      containers:
      - name: frontend
        image: tomdee/hitme
