kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: prevent-dev
  namespace: payment
spec:
  # Apply to all pods in this namespace.
  podSelector:
    matchLabels: {}
  ingress:
    # Only allow connections to TCP 80.
  - ports:
    - port: 80
      protocol: TCP
